services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node-app
        ports:
            - "8080:8080"
        networks:
            - app-network
        env_file:
            - .env
    
    # nginx:
    #     image: nginx:alpine
    #     container_name: nginx
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #         - ./nginx/certs:/etc/nginx/certs
    #     depends_on:
    #         - app
    #     networks:
    #         - app-network

networks:
  app-network:
    driver: bridge